### ISSUE TITLE
What the SSH user and password is ?

### ISSUE THREAD

**Issue by konmin1989** [moode-player/moode#1]
What about the SSH term server's default username and password is? I use the user from Pi is incorrect

**Comment by jesset** [comment]
pi/moodeaudio

**Comment by aero31aero** [comment]
Hi, since this is the first Google result for Moode's ssh info, I like many people must be stumbling here. Moode doesn't have SSH access by default. See issue #612 for more info, or read the new docs.

I suppose 'veterans' who'd just flash the image via dd or something are more likely to get hit with this one, ironically.
