### ISSUE TITLE
Feature Request: Folder support in Playlist Folder

### ISSUE THREAD

**Issue by duracell80** [moode-player/moode#100]
A quick demo of adding a folder and adding a playlist into the folder.
https://youtu.be/cGhYCdaPMfY

Can it be possible to add folders in the playlist share as a "Music Source" in the Library configuration. Currently we can add SMB shares and NAS drives which is cool and I suppose if we had local share on the pi that could be a "source" too. And I suppose something could be done with the SDCARD share where a playlist folder could live there. But yeah currently you can't add folders to the mpd playlist directory and have them in the UI.

I can do it on the SDCARD for sure, but it would be nice to say have a Podcast folder right there in playlists.

**Comment by monkeypox** [comment]
One of the reasons I wanted to move to a menu based view switcher was I want to see playlists moved away from the browse folder view and into their own thing where we can better support them. I did some prelim work on EXTM3U support once upon a time, the basic list can be done easily with mpc -f iirc but we'd need to rework the php that creates the client side data for the lists.

Podcasts would be cool too, I wonder how much work it'd be to subscribe to a feed and then have mode pull in the audio automatically and keep track of position, etc.

**Comment by duracell80** [comment]
Yeah that would be cool, a separate folder like RADIO.

For now I have my podcasts in RADIO/_Podcasts
[https://github.com/duracell80/MoodeRadio-Get/blob/master/scripts/make-radio-manager/radio-folder.png?raw=true](url)

**Comment by facundoq** [comment]
I know this is old, but a clunky workaround for me was to mount the drive via fstab, create a smb share just for the music folder, and mount that share in moode. 
A similar thing could be done with nfs, surely even more efficient, but i wanted to have the share anyway so that was handy.

Since the share is local there's is no network overhead. Obviously the smb protocol is way less efficient than file access. For music playing, however, it doesn't really make a different. I only found significant differences in the scanning speed, which is indeed much slower, but for my use case I dont really care since i don't add folders very often.
