### ISSUE TITLE
ISO Image

### ISSUE THREAD

**Issue by lodgemoorlad** [moode-player/moode#159]
Hi All
Hi guys,my original issues with the ISO is now sorted, sorry for the title. However, 
Could someone tell me if this will work as standalone system that I can control with my phone in my car. Thanks in advance.

**Comment by moodeaudio** [comment]
moOde automatically. boots up in AP mode if no ethernet connection, no defined WiFi SSID, or it fails to get an IP address from a defined WiFi SSID. AP mode startup can take couple minutes on slow, single-core Pi's and moOde is not designed for in-car applications so YMMV.

There are some users though that have moOde rigs in their car. You might want to ask in the Moode Forum since these repos are mainly for dev type stuff.

**Comment by lodgemoorlad** [comment]
Thanks for the quick reply Tim .
Right , got it. Good idea about the forum too. You've saved me a shed load
of frustration trying to understand moodes operating characteristics.
Thanks Alex
