### ISSUE TITLE
Feature Request: Ideas of enhancement for instant play feature

### ISSUE THREAD

**Issue by TookaFace** [moode-player/moode#176]
As suggested by Swizzle, here are some threads with ideas of enhancements for instant play feature:
http://moodeaudio.org/forum/showthread.php?tid=2906
http://moodeaudio.org/forum/showthread.php?tid=2902

**Comment by moodeaudio** [comment]
Now that the new Radio view is mostly done I might be able to look at doing the Add Next/Play Next option where the song or album is queued to the Playlist after the currently playing song or if nothing is playing then queued after the last played song or radio station. Of course any play queue action will turn off Auto-shuffle random play cos it needs exclusive access to the Playlist.

As far as adding options to Instant Play to prevent stray taps I'd propose waiting for more demand for something like this or more issues being posted in the Forum.

One thing about Instant Play (Add/Play) or the plain Add/Play a radio station or a single song is that the code checks to see if the item is already in the Playlist and then just plays that item instead of adding the item again. Whats missing is to check for the presence of a whole album in the Playlist and play that instead of adding it afresh. That would be ideal and would make it easier to hang out in the Library

**Comment by TookaFace** [comment]
For the Play Next option, like turning off Auto-shuffle, i think random need also to be turning off.

With Clear/Play random on can be useful if we want play an album randomly. With Play Next and random on, the whole point of the option will be missed

**Comment by moodeaudio** [comment]
Add next and Play next are now part of upcoming moOde 7 as is the check for whole album already in the play Queue.

As far as turning MPD random play off in addition to turning off Auto-shuffle I'd like to first get some feedback after 7 has been in use for a while.

**Comment by TookaFace** [comment]
Got it, thanks, looking forward to tried it
