### ISSUE TITLE
Configurable UI background blur

### ISSUE THREAD

**Issue by zamiere** [moode-player/moode#478]
Mobile browser freezing because backdrop-filter:blur is time consuming on older hws, please put an option to make it switchable!
Workaround is sed -ri 's/backdrop-filter:blur\(([1-9][0-9]?)px\)/backdrop-filter:blur\(0.\1px\)/g' /var/www/css/styles.min.css

**Comment by moodeaudio** [comment]
How old is the mobile Phone/Browser?

**Comment by zamiere** [comment]
3yrs with Snapdragon 660 SoC and Edge/Chrome

**Comment by moodeaudio** [comment]
Maybe it's unique to that particular phone because my old iPhone SE 1st gen 2017 (Safari) works fine.

You might try posting the issue in the Support section of our Forum. I think I recall some other users reporting hangs or poor performance that they attributed to their huge libraries (70K+ songs). They could try your patch to see of that works for them.

If you need a Forum account email tim at moodeaudio dot org with the userid you would like to use.

**Comment by zamiere** [comment]
Thank you!
