### ISSUE TITLE
Very slow UI response

### ISSUE THREAD

**Issue by jritts** [moode-player/moode#651]
https://drive.google.com/file/d/1dTXJG3gpOtP44LnMlLwlc5Pd0FLBvTi5/view?usp=drivesdk

Here's a video of me trying to navigate as rapidly as possible.  UI interactions all take >1 second to respond. 

Running on a Pi Zero 2 W, with an Allo miniBOSS DAC.

I'd be happy to debug and profile this myself - any code pointers and/or suggestions for workflow would be much appreciated.

**Comment by moodeaudio** [comment]
Troubleshooting is provided in the Support section of our Forum so that all our users can benefit from the discussion and have an opportunity to try and reproduce your issue.

Email forum at moodeaudio dot org with the userid you would like to use (at least 5 characters) and an account will be created for you.
