### ISSUE TITLE
UI rewrite

### ISSUE THREAD

**Issue by ekozan** [moode-player/moode#67]
Hi 

I dont know if this idea will be loved :D 

But I start to rewrite all the UI to Angular, why for fun and for more modularity and Internationalization (i18n)
and code cleaning 

I can show you an POF in 2 week or less i already got the player working great 

My idea is to upgrade adaptative option for feat to smartphone and 7" 

If you love that i'll try to port every curent option to angular 

Max,

Todo List : 

- [ ] Player 50%
- [ ] Explorer 30%
- [ ] Menu 10%
- [ ] Search
- [ ] Radio
- [ ] Config Panel
- [ ] Background Image 80% ( need configuration linked to config panel ) 
- [ ] Screensaver 
- [ ] External source handle ( spotify, .... )

**Comment by moodeaudio** [comment]
Hi Max,

I'm always interested in improving moOde but the challenge is that no one on the moOde project has any experience with Angular.

-Tim

**Comment by monkeypox** [comment]
Hi Maxine,

It won’t be unloved. :) It might be easier to aim for “moode next” rather than try to recreate absolutely everything. Talk to Tim 1-on-1 and see what features are essential to moode and work towards that.

I have some in-progress ui I can send as your project progresses so you can skate to where the puck is headed, I don’t think image attachments work in email on a list like this but I can upload to the git thread directly when I have time.

**Comment by monkeypox** [comment]
Here’s one of the main changes - switching to a menu for the different views rather than the button bar which lets us use the middle of the screen for descriptive text.

![97F6482F-733A-4A3F-A547-19DF4A5F6A93](https://user-images.githubusercontent.com/303924/70577296-d6559f00-1b5f-11ea-868d-473351aac9c0.png)

Search is in the menu instead (keyboard cropped):

![0186C8F2-E4CA-403E-86CB-845622467BBB](https://user-images.githubusercontent.com/303924/70577457-25033900-1b60-11ea-885f-b401e14ede9e.jpeg)

Modals no longer have window chrome (large screens it’s centered rather than full screen)

![2C6F5970-F8FF-404C-A2FF-FC284E880EC3](https://user-images.githubusercontent.com/303924/70577543-50862380-1b60-11ea-8e88-7ffe4963fe07.png)

Backdrop options are hidden when alpha = 1 (they wouldn’t show) and as above only the choose or remove button is shown at any one time.

![3B2C15CD-A15C-4C15-B565-8AE360610623](https://user-images.githubusercontent.com/303924/70577721-9f33bd80-1b60-11ea-85aa-175f1935c308.jpeg)

I’ll upload a branch tonight if you want to see it in action though some of the things in there won’t necessarily make it to moode, principally the alternate large screen layout which doubles as a coverview rethink.

**Comment by ekozan** [comment]
I take the idea :D 

For the momment i make the base 

For memory you can follow my work here : https://github.com/ekozan/moode-ui
for the moment no many thing to see ( just a player bar not finished  )

**Comment by ekozan** [comment]
Idea for dont forget and discution : 

Hability to configure action click or touch on something 

Type of click available : 
- Click 
- DblClick
- ContextClick
- Touch 
- HoldTouch 
- Keybord key ? :) ( space, arrows ) 

Action : 
- Play
- Next
- Prev
- Pause
- Open ( info, album in tracks windows etc... )
- Open context menu 
- Add to playlist

**Comment by inta** [comment]
Are you sure Angular is the right choice here? The current web interface based on Bootstrap and jQuery is not the fastest on weak devices and I think Angular will add some more weight on top. I would choose a smaller framework like Mithril, Preact or – if you really need a famous name – Vue. Angular has a really steep learning curve that only pays off for large projects with large teams.

Just my 2 cents as a moode audio user with a web development background.

**Comment by moodeaudio** [comment]
Closed due to lack of activity.
